<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css" integrity="sha512-rO+olRTkcf304DQBxSWxln8JXCzTHlKnIdnMUwYvQa9/Jd4cQaNkItIUj6Z4nvW1dqK0SKXLbn9h4KwZTNtAyw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/php.min.js"
   integrity="sha512-3jC1jPxa1EFMDjrszKdUOQ4MwWCVtk+cbhci1HyBf5n1U9Dkd72d3wMVsmC+xDXSnaLFSiBhkjaQO0ESMdnJiw=="
   crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>hljs.highlightAll();</script>

<section class="text-white body-font bg-gradient-to-br to-blue-900 from-slate-900">
   <div class="container px-5 py-24 mx-auto lg:w-[950px]">
      <div class="flex flex-wrap w-full mb-20 flex-col items-center text-center">
         <h1 class="sm:text-9xl text-2xl font-bold title-font mb-2 text-gray-200 py-4 px-8 space-x-2 rounded-lg text-transparent" style="-webkit-text-stroke-width: 3px; -webkit-text-stroke-color: white;"><span>Slim</span><span class="italic">X</span></h1>
         <h2 class="sm:text-1xl text-2xl font-medium title-font mb-2 text-gray-200">Slim with superpowers</h2>
         <p class="lg:w-2/3 mt-4 w-full leading-relaxed text-gray-200">Combining Slim with Htmx,
            SlimX aims to streamline backend development by leveraging htmx's capabilities for enhancing web
            applications with minimal JavaScript.</p>
      </div>
      
      <button
         class="flex mx-auto my-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"
      >
         Get Started
      </button>
      
      <div class="flex flex-wrap -m-4">
         <div class="xl:w-1/3 md:w-1/2 p-4">
            <div class="bg-gray-900 bg-opacity-60 p-6 rounded-lg h-full">
               <h2 class="text-lg text-gray-200 font-medium title-font mb-2">PHP</h2>
               <p class="leading-relaxed text-base">With hx-partial, update specific sections of your page in response
                  to HTMX requests, improving user engagement and reducing server load.</p>
            </div>
         </div>
         <div class="xl:w-1/3 md:w-1/2 p-4">
            <div class="bg-gray-900 bg-opacity-60 p-6 rounded-lg h-full">
               <h2 class="text-lg text-gray-200 font-medium title-font mb-2">Slim</h2>
               <p class="leading-relaxed text-base">Leverage the lightweight PHP micro-framework for efficient backend
                  development.</p>
            </div>
         </div>
         <div class="xl:w-1/3 md:w-1/2 p-4">
            <div class="bg-gray-900 bg-opacity-60 p-6 rounded-lg h-full">
               <h2 class="text-lg text-gray-200 font-medium title-font mb-2">Htmx</h2>
               <p class="leading-relaxed text-base">Utilize htmx to add AJAX, CSS Transitions, WebSockets, and Server
                  Sent Events directly in HTML, enhancing your application's interactivity.</p>
            </div>
         </div>
      </div>
   </div>
</section>