<div class="bg-slate-50 flex flex-col items-center justify-center w-full h-full">
   <div class="bg-white px-4 py-4 md:w-[400px] rounded-md shadow-2xl">
      <h2 class="text-lg text-gray-600 font-bold mb-4">Create a new account</h2>
      <div class="space-y-4">
         <hr>
         <div>
            <label for="email">Name</label>
            <input class="control w-full" type="email" name="email" />
         </div>
         <div>
            <label for="email">Email</label>
            <input class="control w-full" type="email" name="email" />
         </div>
         <div>
            <label for="password">Password</label>
            <input class="control w-full" type="password" name="password" />
         </div>
         <div>
            <label for="password">Confirm Password</label>
            <input class="control w-full" type="password" name="password-confirmation" />
         </div>
         <div>
            <a href="/sign-in">Already have an account?</a>
         </div>
         <hr>
         <button class="btn bg-indigo-500 hover:bg-indigo-400 text-white">Create account</button>
      </div>
   </div>
</div>