<form method="post" action="/sign-in" id="content"
   class="bg-slate-50 flex flex-col items-center justify-center w-full h-full">
   <div class="bg-white px-4 py-4 md:w-[400px] rounded-md shadow-2xl">
      <h2 class="text-lg text-gray-600 font-bold mb-4">Sign into your account</h2>
      <div class="space-y-4">
         <hr>
         <div>
            <label for="email">Email</label>
            <input hx-post="/sign-in?hx-validate-email" hx-target="#email-error" class="control w-full" type="email"
               name="email" id="email" value="{{ $email }}" />
            <hx-partial route="/sign-in?hx-validate-email" method="post">
               <div id="email-error">
                  {{isset $errors['email'] }}
                  <span class="text-red-600 text-sm">
                     {{ $errors['email'] }}
                  </span>
                  {{/isset}}
               </div>
            </hx-partial>
         </div>

         <div>
            <label for="password">Password</label>
            <input hx-post="/sign-in?hx-validate-password" hx-target="#password-error"
               hx-trigger="input changed delay:300ms, password" class="control w-full" type="password" name="password"
               id="password" value="{{ $password }}" />
            <hx-partial route="/sign-in?hx-validate-password" method="post">
               <div id="password-error">
                  {{isset $errors['password'] }}
                  <span class="text-red-600 text-sm">
                     {{ $errors['password'] }}
                  </span>
                  {{/isset}}
               </div>
            </hx-partial>
         </div>
         <div>
            <a href="/sign-up">Don't have an account?</a>
         </div>
         <hr>
         <button class="btn bg-indigo-500 hover:bg-indigo-400 text-white">
            Sign in now
         </button>
      </div>
   </div>
</form>