<div class="w-full h-full flex flex-col items-center justify-center">
   <form id="checked-contancts" hx-post="/users" hx-target="#toast" hx-swap="outerHTML">
      <table class="mb-4">
         <thead>
            <tr> 
               <th class="border-2 px-4 py-2">Name</th>
               <th class="border-2 px-4 py-2">Email</th>
               <th class="border-2 px-4 py-2">Active</th>
            </tr>
         </thead>
         <tbody>
            <?php foreach($users as $user ): ?>
               <tr>
                  <td class="border-2 px-4 py-2">{{ $user['name'] }}</td>
                  <td class="border-2 px-4 py-2">{{ $user['email'] }}</td>
                  <td class="border-2 px-4 py-2"><input type="checkbox" name="{{ $user['id'] }}" <?php if($user['active']): ?>checked<?php endif?> /></td>
               </tr>
            <?php endforeach ?>
         </tbody>
      </table>
      
      <button class="btn" type="submit">Bulk Edit</button>
      <hx-partial route="/users" method="post">
         <span id="toast" class="'px-2 py-2 bg-green-300 rounded-md text-green-600 animate-fade-in-out">
            {{isset $message }}
               {{ $message }}
            {{/isset}}
         </span>
      </hx-partial>
   </form>
</div>