<div class="w-full h-full flex flex-col items-center justify-center">
   <form id="checked-contancts" hx-post="/users" hx-target="#toast">
      <table class="mb-4">
         <thead>
            <tr> 
               <th class="border-2 px-4 py-2">Name</th>
               <th class="border-2 px-4 py-2">Email</th>
               <th class="border-2 px-4 py-2">Active</th>
            </tr>
         </thead>
         <tbody>
            <?php foreach($users as $user ): ?>
               <tr>
                  <td class="border-2 px-4 py-2">{{ $user['name'] }}</td>
                  <td class="border-2 px-4 py-2">{{ $user['email'] }}</td>
                  <td class="border-2 px-4 py-2"><input type="checkbox" name="{{ $user['id'] }}" <?php if($user['active']): ?>checked<?php endif?> /></td>
               </tr>
            <?php endforeach ?>
         </tbody>
      </table>
      
      <button class="btn" type="submit">Bulk Edit</button>
      <span id="toast">
         <hx-partial route="/users" method="post">
            <?php if(isset($message)): ?>
               <span class="'px-2 py-2 bg-green-300 rounded-md text-green-600 animate-fade-in-out">
                  {{ $message }}
               </span>
            <?php endif ?>
         </hx-partial>
      </span>
   </form>
</div>